### ISSUE TITLE
Stats Page

### ISSUE THREAD

**Issue by CokkocZateki** [noobscode/Game-Server-Website#4]
Hi
Great Website. One request if possible..

Is it possible for a stats page to be added using [Player Ranks](https://umod.org/plugins/player-rankings) or a Mysql Database?

**Comment by noobscode** [comment]
I Guess this is possible, you would have to store the data using this plugin https://umod.org/plugins/connection-db. This is marked for removal tho and will not be updated. I consider this a huge security risk and think its best not to implement this. You are free to do so youself.

- Install the DB connector plugin. Create a new player_rank.php file.
- Using mysqli or PDO for better security create a connection to DB.
- Create a foreach loop and pull the data from the database table listing the users and their rank.
- Include the file in index.php like the other modules is using **<?php include 'player_rank.php' ?>**
