### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by vMax-dev1** [noobscode/Game-Server-Website#5]
How to change the background color of the site?

**Comment by noobscode** [comment]
Open css/custom.css

**Change this**
```
body {
  padding-top: 56px;
}
```
**Make it look like this**
```
body {
  padding-top: 56px;
  background-color: #YOUR-COLOR-CODE-HERE;
}
```
You can find lots of color codes here:
https://www.w3schools.com/cssref/css_colors.asp

**Comment by noobscode** [comment]
> How to change the background color of the site?

**Open css/custom.css**

**Change this**
```
body {
  padding-top: 56px;
}
```
**Make it look like this**
```
body {
  padding-top: 56px;
  background-color: #YOUR-COLOR-CODE-HERE;
}
```
You can find lots of color codes here:
https://www.w3schools.com/cssref/css_colors.asp

**Comment by vMax-dev1** [comment]
It does not work, the background remains white

**Comment by noobscode** [comment]
> It does not work, the background remains white

Try to do a CTRL + F5 in your browser. The Browser might be caching the CSS from before.
If that doesen't work. Can you paste the output of the custom.css?

If its publicly available. You can also include the link to your page.
